namespace Capstan.Events
{
    public enum EventResolutionType
    {
        Rollback = 0,
        Commit = 1
    }

    /// <summary>
    /// EventType indicates what the event is about
    /// READONLY    A caller has requested information, but nothing should be persisted
    /// WRITE       When a caller intends to do something that alters application state
    /// SERVER      The type generated by the engine for various reasons. 
    ///             It was not created by users and has higher privileges
    /// </summary>
    public enum EventType
    {
        None = 0,
        Readonly,
        Write,
        Server
    }
}
