namespace Capstan.Events
{
    /// <summary>
    /// Events should always strive to create a succesful outcome,
    /// if this is not possible, set state to rollback, which will inform the client and
    /// the event processor to attempt to revert any changes made.
    /// </summary>
    public enum EventResolutionType
    {
        Rollback = 0,
        Commit = 1
    }

    /// <summary>
    /// EventType indicates what the event is about
    /// QUERY       A caller has requested information, but nothing should be persisted
    /// COMMAND     When a caller intends to do something that alters application state
    /// PUSH        The type generated by the engine for distribution unto subscribers,
    ///             
    /// </summary>
    //public enum EventType
    //{
    //    None = 0,
    //    Query,
    //    Command,
    //    Push
    //}
}
